Salesforce LWC/force-app/main/default/objects/Cricketers__c/Cricketers__c.object-meta.xml
<CustomObject>
    <label>Cricketers</label>
    <nameField>
        <label>Cricketers Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Cricketers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Salesforce LWC/force-app/main/default/objects/Cricketers__c/fields/Nationality__c.field-meta.xml
<CustomField>
    <fullName>Nationality__c</fullName>
    <label>Nationality</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Indian</fullName>
            </value>
            <value>
                <fullName>Australian</fullName>
            </value>
            <value>
                <fullName>British</fullName>
            </value>
            <value>
                <fullName>Pakisthan</fullName>
            </value>
            <value>
                <fullName>Itely</fullName>
            </value>
            <value>
                <fullName>bangladesh</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Salesforce LWC/force-app/main/default/objects/Cricketers__c/fields/Runs__c.field-meta.xml
<CustomField>
    <fullName>Runs__c</fullName>
    <label>Runs</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

Salesforce LWC/force-app/main/default/classes/InlineDataTableDemo.cls
public class InlineDataTableDemo {
    @AuraEnabled(cacheable=true)
    public static List<Cricketers__c> getCricketList(string nationality) {
        return [select Id,Name,Nationality__c,Runs__c from Cricketers__c];
    }
    @AuraEnabled
    public static string updateCricketersList(object playersData) {
        system.debug('playersData==>'+playersData);
        List<Cricketers__c> playersDataList =(List<Cricketers__c>) JSON.deserialize(JSON.serialize(playersData), List<Cricketers__c>.Class);
        system.debug('UpdatedplayersDataList==>'+playersDataList);
        if(!playersDataList.isEmpty()){
            update playersDataList;
            return 'Success';
        }
        return 'failed';
    }
}