Salesforce LWC/force-app/main/default/objects/Cricketers__c/Cricketers__c.object-meta.xml
<CustomObject>
    <label>Cricketers</label>
    <nameField>
        <label>Cricketers Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Cricketers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Salesforce LWC/force-app/main/default/objects/Cricketers__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.Active__c</field>
            <operation>equals</operation>
            <value>Yes</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Cricketers</relationshipLabel>
    <relationshipName>Cricketers</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

Salesforce LWC/force-app/main/default/classes/newApexRun.cls
public class newApexRun {
    public static void newMethod(){
        Map<Id,Cricketers__c> CricketersMap = new Map<Id,Cricketers__c>();
      List<Cricketers__c> CricketersList=[SELECT Id, Account__r.Phone FROM Cricketers__c where Id ='a005g00003FxICPAA3'];  
        for(Cricketers__c crick:CricketersList){
           // system.debug(crick.Account__r.Phone); Here we get Phone
            CricketersMap.put(crick.Id,crick);
        }
         //system.debug('get The Phone '+CricketersMap.get('a005g00003FxICPAA3')); here we will not get Phone
         //Solution 1: Line: 10, Column: 1 System.SObjectException: Invalid field Account__r.Phone for Cricketers__c 
         //error occure
       //  system.debug('get The Phone '+CricketersMap.get('a005g00003FxICPAA3').get('Account__r.Phone'));
         //Solution 2:      
         system.debug('get The Phone '+CricketersMap.get('a005g00003FxICPAA3').getSobject('Account__r').get('Phone'));
    }
}