Salesforce LWC/force-app/main/default/objects/Cricketers__c/Cricketers__c.object-meta.xml
<CustomObject>
    <label>Cricketers</label>
    <nameField>
        <label>Cricketers Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Cricketers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Salesforce LWC/force-app/main/default/objects/Cricketers__c/fields/Age__c.field-meta.xml
<CustomField>
    <fullName>Age__c</fullName>
    <label>Age</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

Salesforce LWC/force-app/main/default/objects/Cricketers__c/fields/Image_Url__c.field-meta.xml
<CustomField>
    <fullName>Image_Url__c</fullName>
    <label>Image Url</label>
    <type>Url</type>
</CustomField>

Salesforce LWC/force-app/main/default/objects/Cricketers__c/fields/Nationality__c.field-meta.xml
<CustomField>
    <fullName>Nationality__c</fullName>
    <label>Nationality</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Indian</fullName>
            </value>
            <value>
                <fullName>Australian</fullName>
            </value>
            <value>
                <fullName>British</fullName>
            </value>
            <value>
                <fullName>Pakisthan</fullName>
            </value>
            <value>
                <fullName>Itely</fullName>
            </value>
            <value>
                <fullName>bangladesh</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Salesforce LWC/force-app/main/default/objects/Cricketers__c/fields/Runs__c.field-meta.xml
<CustomField>
    <fullName>Runs__c</fullName>
    <label>Runs</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

Salesforce LWC/force-app/main/default/classes/CricketerController1.cls
public class CricketerController1 {
    @AuraEnabled(cacheable=true)
    public static List<Cricketers__c> getCricketList(string nationality) {
        if(nationality==''){
            return [select Id,Name,Nationality__c,Age__c,Runs__c,Image_Url__c from Cricketers__c];
        }
        else{
            return [select Id,Name,Nationality__c,Age__c,Runs__c,Image_Url__c from Cricketers__c where Nationality__c=:nationality];
        }
        
        
    }
    
     @AuraEnabled()
    public static Cricketers__c getSelectedPlayerDetailt(string playerId){
        return [select Id,Name,Nationality__c,Age__c,Runs__c,Image_Url__c from Cricketers__c where Id=:playerId];
    }
}