Salesforce LWC/force-app/main/default/objects/System_Event__c/System_Event__c.object-meta.xml
<CustomObject>
    <label>System Event</label>
    <nameField>
        <displayFormat>Event-{000000}</displayFormat>
        <label>EventId</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>System Events</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Salesforce LWC/force-app/main/default/objects/System_Event__c/fields/Complete_Trace_string__c.field-meta.xml
<CustomField>
    <fullName>Complete_Trace_string__c</fullName>
    <label>Complete Trace string</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

Salesforce LWC/force-app/main/default/objects/System_Event__c/fields/Component_Type__c.field-meta.xml
<CustomField>
    <fullName>Component_Type__c</fullName>
    <label>Component Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Apex Class</fullName>
            </value>
            <value>
                <fullName>Apex Trigger</fullName>
            </value>
            <value>
                <fullName>Lightning Flow</fullName>
            </value>
            <value>
                <fullName>Platform Event</fullName>
            </value>
            <value>
                <fullName>Batch Apex</fullName>
            </value>
            <value>
                <fullName>Queueable Apex</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Salesforce LWC/force-app/main/default/objects/System_Event__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>System_Events</relationshipName>
    <type>Lookup</type>
</CustomField>

Salesforce LWC/force-app/main/default/classes/QueableUpdateParentAccount.cls
public class QueableUpdateParentAccount implements Queueable{
    
    Private List<Account> accList;
    Private Id parentAccId;
    
    Public QueableUpdateParentAccount(List<Account> accRecords, Id id){
        this.accList = accRecords;
        this.parentAccId = id;
    }
    Public void Execute(QueueableContext qc){
        try{
            for(Account acc : accList){
                acc.ParentId = parentAccId;
            }
            Update accList;
        }
        catch(System.Exception ex){
            System_Event__c sysEvent = new System_Event__c();
            sysEvent.Complete_Trace_string__c=ex.getStackTraceString();
            sysEvent.Component_Name__c='ExceptionClass';
            sysEvent.Component_Type__c='Queueable Apex Class';
            sysEvent.Exception_Type__c=ex.getTypeName();
            sysEvent.Line_Number__c=Integer.valueOf(ex.getLineNumber());
            sysEvent.Message__c=ex.getMessage();
            sysEvent.User__c=UserInfo.getUserId();
            insert sysEvent;
        }
    }
    
}